on:
  - "push"

jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    name: "Create djorigin/angular:17-alpine"
    steps:
      - name: "Docker info"
        id: step_dockerinfo
        run: |
          echo $(docker info)
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build docker image"
        id: step_buildimage
        run: |
          docker build -t angular:17.${{ github.run_number }}-alpine -f ./src/Dockerfile .
