on:
  - "push"

jobs:


  create_docker_image:
    runs-on: ubuntu-latest
    name: "Create djorigin/angular:17-alpine"
    steps:
      - name: "Docker info"
        run: |
          echo $(docker info)
      
      - name: "Checkout"
        uses: actions/checkout@v4        

      - name: "Set tags"
        run: |
          IMAGE_NAME=djorigin/angular17
          echo "TAG_LATEST=${IMAGE_NAME}:latest" >> $GITHUB_ENV
          echo "TAG_NUMBER=${IMAGE_NAME}:${{ github.run_number }}" >> $GITHUB_ENV

      - name: "Build docker image"
        run: |
          docker build -t ${{ env.TAG_LATEST }} -t ${{ env.TAG_NUMBER }} -f ./src/Dockerfile .

      - name: "Login to Docker hub"
        run: |
          docker login -u ${{ vars.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push to docker.io public registry"
        run: |
          docker push -a djorigin/angular17